### ISSUE TITLE
SynthaxError

### ISSUE THREAD

**Issue by hayriokcu** [jvns/svg2notability#3]
This work is awesome. But I had some problems (I have poor knowledge of coding). 
When I use svg2notability.py I receive below error.

```
host0512:svg2notability-master macbook$ python svg2notability.py my-file.svg
  File "svg2notability.py", line 26
    ,
    ^
SyntaxError: invalid syntax
```

Alsp test_to_notability.py gives following error.

```
host0512:svg2notability-master macbook$ python test_to_notability.py
Traceback (most recent call last):
  File "test_to_notability.py", line 1, in <module>
    from to_notability import *
  File "/Users/macbook/.Trash/svg2notability-master/to_notability.py", line 1, in <module>
    import svgpathtools
ImportError: No module named svgpathtools
```
thanks for your reply in advance!

**Comment by schanzerman** [comment]
This work is awesome. But I had some problems (I have poor knowledge of coding). 
When I use svg2notability.py I receive below error.

```
host0512:svg2notability-master macbook$ python svg2notability.py my-file.svg
  File "svg2notability.py", line 26
    ,
    ^
SyntaxError: invalid syntax
```

Alsp test_to_notability.py gives following error.

```
host0512:svg2notability-master macbook$ python test_to_notability.py
Traceback (most recent call last):
  File "test_to_notability.py", line 1, in <module>
    from to_notability import *
  File "/Users/macbook/.Trash/svg2notability-master/to_notability.py", line 1, in <module>
    import svgpathtools
ImportError: No module named svgpathtools
```
thanks for your reply in advance!

**Comment by basta** [comment]
Not the maintainer, but pretty sure that this program is written in python 2. As for svgpathtools you need to install that using python -m pip install svgpathtools
